
name: release-please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: terraform-module
          package-name: terraform-gcs-remote-state-bootstrap
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          extra-files: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
